name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Builds the documentation website under ./build/html
      # With the -s flag, it only builds Sphinx documentation
      - name: Build Documentation
        run: |
          cd docs
          .\build_docs.bat -s

      # Deploys the website to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .\docs\build\html
